---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creating EC2 Instance with security group by enabling port 80 and 22(SSH) and S3 Bucket

Resources:
 Codebuild:
  Type: AWS::CodeBuild::Project
  Properties:
    Name: cftcodebuild
    Description: Creating ec2 instance using code build
    ServiceRole: arn:aws:iam::442149536863:role/service-role/codebuild-test2-service-role
    LogsConfig:
      CloudWatchLogs:
        Status: ENABLED
    Artifacts:
      Type: no_artifacts
    Environment:
      Type: LINUX_CONTAINER
      ComputeType: BUILD_GENERAL1_SMALL
      Image: aws/codebuild/java:openjdk-8
    Source:
      Auth:
       Type: OAUTH
      Location: https://github.com/gamidirakesh/AWS-CFT.git
      Type: GITHUB
    TimeoutInMinutes: 30
    # VpcConfig:
    #   SecurityGroupIds: 
    #    - sg-05f5edce3f357f202
    #   Subnets: 
    #    - subnet-0c3e0fd92fa47bd30
    #   VpcId: "vpc-04b240756e515b6cc"
    Tags:
      - Key: Key1
        Value: Value1